### ISSUE TITLE
引用的 前人的翻译 应当如何标识出来？

### ISSUE THREAD

**Issue by run-ze** [virtoolswebplayer/typescript-book-chinese#2]
在进行翻译时，有一些部分参考了[前人的翻译](https://github.com/ZenDay/TypeScipt-Deep-Dive-chinese-version)。
是否应该把这些部分标识出来？
如何标识出来？
或者我们应该避免参考 前人的翻译？

**Comment by virtoolswebplayer** [comment]
在开头或结尾要声明参考出处 把作者的github 帐号和地址带上，已与《TypeScipt-Deep-Dive-chinese-version》原译者ZenDay取得联系，已同意我们引用其已翻译的部分

https://github.com/ZenDay/TypeScipt-Deep-Dive-chinese-version/issues/2
